In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('creditcard.csv')
df.head()


Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.tail()

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 31 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [5]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
normal = df[df.Class == 0]
fraud = df[df.Class == 1]
print(normal.shape)
print(fraud.shape)

(284315, 31)
(492, 31)


In [8]:
#static value of amount
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [9]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [10]:
#compare the both value
df.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

In [11]:
#Build a sample dataset containig similardistribution
normal_sample = normal.sample(n=492)
df1 = pd.concat([normal_sample,fraud], axis=0)
df1.head()

Time        V1        V2        V3        V4        V5        V6  \
24744    33362.0  1.121491 -0.946323  0.437724 -0.748922 -1.111741 -0.403156   
32572    36855.0  0.258710 -1.315833  0.404775  1.118264 -0.283324  1.881561   
21179    31521.0 -3.656307  2.143605 -0.619436 -0.751792 -1.130467  1.631354   
91182    63347.0 -0.922913  0.966578  0.982686  0.214601 -1.404790 -0.681641   
258089  158487.0  2.129891  0.002894 -1.479417  0.150307  0.506737 -0.500767   

              V7        V8        V9  ...       V21       V22       V23  \
24744  -0.582528 -0.042594 -0.979918  ...  0.104703 -0.131058 -0.074003   
32572  -0.298830  0.624569  0.148387  ...  0.562493  0.948261 -0.304393   
21179  -1.776657  2.997719 -0.077941  ...  0.368690  0.967756  0.000434   
91182  -0.602287  0.921852  0.006443  ...  0.180378  0.148734  0.215783   
258089  0.228074 -0.310053  0.429958  ... -0.339042 -0.769613  0.203715   

             V24       V25       V26       V27       V28  Amount  Class  
24744  -0.003195  0.217446 -0.422956 -0.009860  0.034590  142.46      0  
32572  -1.002235  0.041717 -0.186385  0.044572  0.070705  374.00      0  
21179  -1.300751 -0.032577  0.601557  0.205064  0.039233   25.65      0  
91182   0.351933 -0.627017  0.176240 -0.312706 -0.119012   32.50      0  
258089 -1.030338 -0.132534  0.262142 -0.060905 -0.068704    0.89      0  

[5 rows x 31 columns]

In [12]:
df1.tail()

Time        V1        V2        V3        V4        V5        V6  \
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[5 rows x 31 columns]

In [13]:
df1['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [14]:
df1.shape

(984, 31)

In [15]:
df1.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94029.930894  0.000717 -0.009085  0.058377  0.049149 -0.142770   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0     -0.039349  0.003213  0.061768  0.009466  ... -0.017498  0.057602   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.010124  0.003599  0.020315 -0.064590  0.037661 -0.008246  0.002120   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       95.791585  
1      122.211321  

[2 rows x 30 columns]

# Model

In [16]:
X=df1.drop('Class',axis=1)
Y=df1['Class']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)


# Logistic Rrgression

In [18]:
model = LogisticRegression()
model.fit(X_train, Y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
# For Training data 
X_train_prediction = model.predict(X_train)
train_accuracy=accuracy_score(X_train_prediction,Y_train)
print('X_train_prediction: ', train_accuracy)

X_train_prediction:  0.9479034307496823


In [20]:
#For Test data
X_test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(X_test_prediction, Y_test)
print('X_test_prediction: ',test_accuracy)

#both are similar so good

X_test_prediction:  0.9086294416243654


# RandomForestClassifier

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a random forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=2)
clf.fit(X_train, Y_train)

RandomForestClassifier(random_state=2)

In [23]:
# For Train data
y_pred = clf.predict(X_train)
print('Train_Accuracy: ',accuracy_score(Y_train, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_train, y_pred))
print("\nClassification Report:\n", classification_report(Y_train, y_pred))

Train_Accuracy:  1.0

Confusion Matrix:
 [[393   0]
 [  0 394]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       393
           1       1.00      1.00      1.00       394

    accuracy                           1.00       787
   macro avg       1.00      1.00      1.00       787
weighted avg       1.00      1.00      1.00       787



In [24]:
# For Test data 
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))

Accuracy: 0.9187817258883249

Confusion Matrix:
 [[95  4]
 [12 86]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.96      0.92        99
           1       0.96      0.88      0.91        98

    accuracy                           0.92       197
   macro avg       0.92      0.92      0.92       197
weighted avg       0.92      0.92      0.92       197



# Isolation Forest

In [25]:
from sklearn.ensemble import IsolationForest

In [26]:
# Isolation Forest
iso_forest = IsolationForest(contamination=0.01, random_state=2)
iso_forest.fit(X_train)

# Predictions
y_pred_iso = iso_forest.predict(X_test)
y_pred_iso = [1 if x == -1 else 0 for x in y_pred_iso]

In [27]:
# Test data
print("Accuracy:", accuracy_score(Y_test, y_pred_iso))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_iso))
print("Classification Report:\n", classification_report(Y_test, y_pred_iso))

Accuracy: 0.5076142131979695
Confusion Matrix:
 [[99  0]
 [97  1]]
Classification Report:
               precision    recall  f1-score   support

           0       0.51      1.00      0.67        99
           1       1.00      0.01      0.02        98

    accuracy                           0.51       197
   macro avg       0.75      0.51      0.35       197
weighted avg       0.75      0.51      0.35       197



# MLP Classifier (Neural_Network)

In [28]:
from sklearn.neural_network import MLPClassifier

In [29]:
#  Neural Network
neural_network = MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=1000, activation='relu', random_state=42)
neural_network.fit(X_train, Y_train)
y_pred_nn = neural_network.predict(X_test)

In [30]:
#test data
print("\nNeural Network:")
print(f"Accuracy: {accuracy_score(Y_test, y_pred_nn)}")
print("Classification Report:")
print(classification_report(Y_test, y_pred_nn))
print("Confusion Matrix:")
print(confusion_matrix(Y_test, y_pred_nn))


Neural Network:
Accuracy: 0.8883248730964467
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.92      0.89        99
           1       0.91      0.86      0.88        98

    accuracy                           0.89       197
   macro avg       0.89      0.89      0.89       197
weighted avg       0.89      0.89      0.89       197

Confusion Matrix:
[[91  8]
 [14 84]]
